djcrm/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('leads/', include('leads.urls', namespace='leads')),
]

leads/urls.py
from django.urls import path
from .views import *

app_name = 'leads'

urlpatterns = [
    path('', lead_list, name='lead-list'),
    path('<int:pk>/', lead_detail, name='lead-detail'),
    path('<int:pk>/update', lead_update, name='lead-update'),
    path('<int:pk>/delete', lead_delete, name='lead-delete'),
    path('create/', lead_create, name='lead-create')
]

leads/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
  pass


class Lead(models.Model):

  SOURCE_CHOICES = (
    ('YouTube', 'YouTube'),
    ('Google', 'Google'),
    ('Newsletter', 'Newsletter'),
    ('LinkedIn', 'LinkedIn'),
  )

  first_name = models.CharField(max_length=20)
  last_name = models.CharField(max_length=20)
  age = models.IntegerField(default=0)

  phoned = models.BooleanField(default=False)
  source = models.CharField(choices=SOURCE_CHOICES, max_length=100)

  #profile_picture = models.ImageField(blank=True, null=True)
  #special_files = models.FileField(blank=True, null=True)
  agent = models.ForeignKey("Agent", on_delete=models.CASCADE)

  def __str__(self):
    return f"{self.first_name} {self.last_name}"

class Agent(models.Model):
  user = models.OneToOneField(User, on_delete=models.CASCADE)

  def __str__(self):
    return self.user.username

leads/forms.py
from django import forms
from .models import Lead

class LeadModelForm(forms.ModelForm):
    class Meta:
        model = Lead
        fields = [
            'first_name',
            'last_name',
            'age',
            'phoned',
            'source',
            'agent'
        ]

class LeadForm(forms.Form):
  SOURCE_CHOICES = (
    ('YouTube', 'YouTube'),
    ('Google', 'Google'),
    ('Newsletter', 'Newsletter'),
    ('LinkedIn', 'LinkedIn'),
  )
  first_name = forms.CharField(max_length=100)
  last_name = forms.CharField(max_length=100)
  # email = forms.EmailField()
  age = forms.IntegerField(min_value=0)
  phoned = forms.BooleanField(required=False)
  source = forms.ChoiceField(choices=SOURCE_CHOICES)

leads/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Lead, Agent
from .forms import LeadForm, LeadModelForm

def lead_list(request):
    #return HttpResponse('home.html')
    leads = Lead.objects.all()
    context = {"leads":leads}
    return render(request, 'lead_list.html', context)

def lead_detail(request, pk):
    print(pk)
    # return HttpResponse('detail.html')
    lead = Lead.objects.get(id=pk)
    print(lead)
    context = {"lead":lead}
    return render(request, 'lead_detail.html', context)

# def lead_create(request):
#   form = LeadForm()
#   if request.method == 'POST':
#     print('receiving a post request')
#     form = LeadForm(request.POST)
#     if form.is_valid():
#       print('form is valid')
#       print(form.cleaned_data)
#       first_name = form.cleaned_data['first_name']
#       last_name = form.cleaned_data['last_name']
#       age = form.cleaned_data['age']
#       phoned = form.cleaned_data['phoned']
#       source = form.cleaned_data['source']
#       agent = Agent.objects.first()
#       Lead.objects.create(first_name=first_name, last_name=last_name, age=age, phoned=phoned, source=source, agent=agent)
#       print('Lead has created')
#       return redirect('/leads')
#   context = {"form":form}
#   return render(request, 'lead_create.html', context)

def lead_create(request):
  form = LeadModelForm()
  if request.method == 'POST':
    print('receiving a post request')
    form = LeadModelForm(request.POST)
    if form.is_valid():
      print('form is valid')
      print(form.cleaned_data)
      form.save()
      print('Lead has created')
      return redirect('/leads')
  context = {"form":form}
  return render(request, 'lead_create.html', context)

def lead_update(request, pk):
  lead = Lead.objects.get(id=pk)
  form = LeadModelForm(instance=lead)
  if request.method == 'POST':
    print('receiving a post request')
    form = LeadModelForm(request.POST, instance=lead)
    if form.is_valid():
      print('form is valid')
      print(form.cleaned_data)
      form.save()
      print('Lead has updated')
      return redirect('/leads')
  context = {"form":form, "lead":lead}
  return render(request, 'lead_update.html', context)

def lead_delete(request, pk):
  lead = Lead.objects.get(id=pk)
  lead.delete()
  return redirect('/leads')
  # context = {"lead":lead}
  # return render(request, 'lead_delete.html', context)

leads/templates/leads/home_page.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h1>Hello World</h1>
  <p>This is first page</p>
</body>
</html>

templates/lead_create.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Document</title>
    <style>
      .lead {
        font-size: 1.5em;
        background-color: #ffc107;
        padding: 5px;
        border-radius: 10px;
        margin: 10px;
        width: 500px;
      }
      h1 {
        font-size: 3em;
      }
    </style>
  </head>
  <body>
    <a href="{% url 'leads:lead-list' %}">Go Back to Leads</a>
    <h1>Create Lead:</h1>
    <form action="." method="POST">
      {% csrf_token %}
      {{form.as_p}}
      <button type="submit">Create Lead</button>
    </form>
  </body>
</html>

templates/lead_detail.html
<!DOCTYPE html>
<html lang="en">
  <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <meta http-equiv="X-UA-Compatible" content="ie=edge">
      <title>Document</title>
      <style>
        .lead {
          font-size: 1.5em;
          background-color: #ffc107;
          padding: 5px;
          border-radius: 10px;
          margin: 10px;
          width: 400px;
        }
      </style>
  </head>
  <body>
  <a href="{% url 'leads:lead-list' %}">Go Back to Leads</a>
  <hr />
  <hr />
    <h1>Lead Information</h1>
    <ul>
      <li class="lead">
      {{lead}} </li>
      <li class="lead">
      Age: {{lead.age}} </li>
      <li class="lead">
      Source: {{lead.source}} </li>
      <li class="lead">
      Phoned: {{lead.phoned}} </li>
      <li class="lead">
      Responsible Agent: {{lead.agent}} </li>
    </ul>
    <hr />
    <a href="{% url 'leads:lead-update' lead.pk %}">Edit</a>
    <a href="{% url 'leads:lead-delete' lead.pk %}">Delete</a>
  </body>
</html>

templates/lead_list.html
<!DOCTYPE html>
<html lang="en">
  <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <meta http-equiv="X-UA-Compatible" content="ie=edge">
      <title>Document</title>
      <style>
        .lead {
          font-size: 1.5em;
          background-color: #ffc107;
          padding: 5px;
          border-radius: 10px;
          margin: 10px;
          width: 500px;
        }
        h1{
          font-size: 3em;
        }
      </style>
  </head>
  <body>
    <a href="{% url 'leads:lead-create' %}">Create a new Lead</a>
    <hr />
    <h1>Lead List</h1>
    <h3>This is all our leads: </h3>
    <ul>
      {% for lead in leads %}
      <a href="{% url 'leads:lead-detail' lead.pk %}"><li class="lead">{{lead}} </a> // Source: {{lead.source}}  </li>
      {% endfor %}
    </ul>

  </body>
</html>

templates/lead_update.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Document</title>
    <style>
      .lead {
        font-size: 1.5em;
        background-color: #ffc107;
        padding: 5px;
        border-radius: 10px;
        margin: 10px;
        width: 500px;
      }
      h1 {
        font-size: 3em;
      }
    </style>
  </head>
  <body>
    <a href="{% url 'leads:lead-detail' lead.pk %}">Go Back to {{lead}}</a>
    <h1>Update Lead: {{lead}}</h1>
    <form method="POST">
      {% csrf_token %}
      {{form.as_p}}
      <button type="submit">Save Lead</button>
    </form>
  </body>
</html>